-- SQL compatible con phpMyAdmin (MySQL/MariaDB)
SET SQL_MODE='ANSI_QUOTES';
SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE IF NOT EXISTS "migrations" ("id" int NOT NULL AUTO_INCREMENT PRIMARY KEY, "migration" varchar(255) not null, "batch" int not null);
INSERT INTO migrations VALUES(1,'2014_10_12_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'2014_10_12_100000_create_password_resets_table',1);
INSERT INTO migrations VALUES(3,'2019_08_19_000000_create_failed_jobs_table',1);
INSERT INTO migrations VALUES(4,'2021_07_03_222324_create_topics_categories_table',1);
INSERT INTO migrations VALUES(5,'2021_07_03_231719_create_topics_table',1);
INSERT INTO migrations VALUES(6,'2021_07_05_234146_create_topics_comments_table',1);
INSERT INTO migrations VALUES(7,'2021_07_06_090104_add_profile_image_to_users',1);
INSERT INTO migrations VALUES(8,'2021_07_06_211805_add_name_to_users',1);
INSERT INTO migrations VALUES(9,'2021_07_07_222602_create_article_categories_table',1);
INSERT INTO migrations VALUES(10,'2021_07_07_222701_create_articles_table',1);
INSERT INTO migrations VALUES(11,'2021_07_08_124840_create_slides_table',1);
INSERT INTO migrations VALUES(12,'2021_07_08_180948_add_topics_comments_count_to_users',1);
INSERT INTO migrations VALUES(13,'2021_07_08_205857_add_some_tables_to_topics_comments',1);
INSERT INTO migrations VALUES(14,'2021_07_14_101256_create_articles_comments_table',1);
INSERT INTO migrations VALUES(15,'2022_01_25_210728_create_users_bans_table',1);
INSERT INTO migrations VALUES(16,'2022_01_25_211235_create_users_warnings_table',1);
INSERT INTO migrations VALUES(17,'2022_01_26_095001_add_disabled_to_users_table',1);
INSERT INTO migrations VALUES(18,'2022_01_26_101825_create_users_logs_table',1);
INSERT INTO migrations VALUES(19,'2022_01_28_184554_add_ip_columns_to_users_table',1);
INSERT INTO migrations VALUES(20,'2022_01_28_220507_create_navigations_table',1);
INSERT INTO migrations VALUES(21,'2022_01_29_002121_create_badges_table',1);
INSERT INTO migrations VALUES(22,'2022_01_31_224947_add_forum_signature_to_users_table',1);
INSERT INTO migrations VALUES(23,'2022_02_01_232811_create_user_notifications_table',1);
INSERT INTO migrations VALUES(24,'2022_02_04_104301_create_furni_values_table',1);
INSERT INTO migrations VALUES(25,'2026_02_25_202500_add_unique_index_to_users_username',2);
INSERT INTO migrations VALUES(26,'2026_02_25_211000_add_habbo_verification_columns_to_users_table',3);
CREATE TABLE IF NOT EXISTS "users" ("id" int NOT NULL AUTO_INCREMENT PRIMARY KEY, "username" varchar(255) not null, "password" varchar(255) not null, "email" varchar(255) not null, "email_verified_at" datetime, "remember_token" varchar(255), "created_at" datetime, "updated_at" datetime, "profile_image_path" varchar(255) not null default 'profiles/default.png', "name" varchar(255), "topics_comment_count" int not null default '0', "disabled" tinyint(1) not null default '0', "ip_register" varchar(255) not null, "ip_last_login" varchar(255) not null, "last_login" datetime not null, "forum_signature" text, "habbo_name" varchar(255), "habbo_hotel" varchar(255), "habbo_verification_code" varchar(255), "habbo_verified_at" datetime);
INSERT INTO users VALUES(1,'Admin','$2y$10$7FAYVfP3KitrHfk5LXuTxubbCkRzwMRz0DO1AI2isyHMlabhYbF7u','admin@admin.com',NULL,NULL,'2026-02-25 16:19:49','2026-02-25 16:19:49','profiles/default.png','Administrator',0,0,'localhost','localhost','2026-02-25 16:19:49',NULL,NULL,NULL,NULL,NULL);
CREATE TABLE IF NOT EXISTS "password_resets" ("email" varchar(255) not null, "token" varchar(255) not null, "created_at" datetime);
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" int NOT NULL AUTO_INCREMENT PRIMARY KEY, "uuid" varchar(255) not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime default CURRENT_TIMESTAMP not null);
CREATE TABLE IF NOT EXISTS "topics_categories" ("id" int NOT NULL AUTO_INCREMENT PRIMARY KEY, "name" varchar(255) not null, "icon" varchar(255));
INSERT INTO topics_categories VALUES(1,'HabboAcademy',NULL);
INSERT INTO topics_categories VALUES(2,'Presentación',NULL);
INSERT INTO topics_categories VALUES(3,'Dudas',NULL);
INSERT INTO topics_categories VALUES(4,'Novedades',NULL);
INSERT INTO topics_categories VALUES(5,'Eventos/Promociones',NULL);
INSERT INTO topics_categories VALUES(6,'Videos/Música',NULL);
INSERT INTO topics_categories VALUES(7,'Habbo',NULL);
INSERT INTO topics_categories VALUES(8,'Juegos',NULL);
INSERT INTO topics_categories VALUES(9,'Sugerencias',NULL);
INSERT INTO topics_categories VALUES(10,'Humor',NULL);
INSERT INTO topics_categories VALUES(11,'Otros',NULL);
INSERT INTO topics_categories VALUES(12,'Intercambios y negocios',NULL);
INSERT INTO topics_categories VALUES(13,'Curiosidades',NULL);
CREATE TABLE IF NOT EXISTS "topics" ("id" int NOT NULL AUTO_INCREMENT PRIMARY KEY, "title" varchar(255) not null, "category_id" int not null, "user_id" int not null, "content" text not null, "moderated" varchar(255) not null default 'pending', "moderator" varchar(255), "slug" varchar(255) not null, "fixed" tinyint(1) not null default '0', "status" tinyint(1) not null default '1', "comments_count" int not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("category_id") references "topics_categories"("id"), foreign key("user_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "topics_comments" ("id" int NOT NULL AUTO_INCREMENT PRIMARY KEY, "user_id" int not null, "topic_id" int not null, "content" text not null, "created_at" datetime, "updated_at" datetime, "active" tinyint(1) not null default '1', "moderated" varchar(255) not null default 'pending', "moderator" varchar(255), foreign key("user_id") references "users"("id"), foreign key("topic_id") references "topics"("id"));
CREATE TABLE IF NOT EXISTS "articles_categories" ("id" int NOT NULL AUTO_INCREMENT PRIMARY KEY, "name" varchar(255) not null, "icon" varchar(255));
INSERT INTO articles_categories VALUES(1,'HabboAcademy',NULL);
INSERT INTO articles_categories VALUES(2,'Novedades',NULL);
INSERT INTO articles_categories VALUES(3,'Promociones/Eventos',NULL);
INSERT INTO articles_categories VALUES(4,'Videos/Música',NULL);
INSERT INTO articles_categories VALUES(5,'Habbo',NULL);
INSERT INTO articles_categories VALUES(6,'Juegos',NULL);
INSERT INTO articles_categories VALUES(7,'Temas externos',NULL);
INSERT INTO articles_categories VALUES(8,'Otros',NULL);
CREATE TABLE IF NOT EXISTS "articles" ("id" int NOT NULL AUTO_INCREMENT PRIMARY KEY, "user_id" int not null, "category_id" int not null, "title" varchar(255) not null, "description" varchar(255) not null, "image_path" varchar(255) not null, "slug" varchar(255) not null, "content" text not null, "reviewed" tinyint(1) not null default '0', "reviewer" varchar(255), "status" tinyint(1) not null default '0', "fixed" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id"), foreign key("category_id") references "articles_categories"("id"));
INSERT INTO articles VALUES(1,1,1,'Bem-vindo à HabboAcademy!','HabboAcademy é uma CMS open-source para fã-sites Habbo.','https://habboassets.com/assets/images/web-promos/lpromo_h15generic2.png','bem-vindo-a-habboacademy',replace('\n                    <center>\n                        <img class="d-block mb-4" src="https://1.bp.blogspot.com/-u9o-Bvx9lnQ/Vt5ENzbIcOI/AAAAAAAAkdw/-5teG4gKbk4/s1600/541661190.png" />\n                        <span class="d-block">HabboAcademy instalada com sucesso! Obrigado pela preferência.</span>\n                        <strong></> por Nicollas#8412</strong>\n                    </center>\n                ','\n',char(10)),1,'Admin',1,1,'2026-02-25 16:19:49','2026-02-25 16:19:49');
CREATE TABLE IF NOT EXISTS "slides" ("id" int NOT NULL AUTO_INCREMENT PRIMARY KEY, "title" varchar(255) not null, "description" varchar(255) not null, "slug" varchar(255) not null, "image_path" varchar(255) not null, "active" tinyint(1) not null default '0', "fixed" tinyint(1) not null default '0', "new_tab" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime);
INSERT INTO slides VALUES(1,'HabboAcademy instalado con éxito','Programado con mucho café y esfuerzo por Nicollas#8412','#','https://i.imgur.com/Wx9WzhF.gif',1,1,0,'2026-02-25 16:19:49','2026-02-25 16:19:49');
INSERT INTO slides VALUES(2,'HabboAcademy Discord','Entra en nuestro Discord','https://discord.gg/dzjhdusRW2','https://images.habbo.com/web_images/habbo-web-articles/lpromo_genericval16.png',1,0,1,'2026-02-25 16:19:49','2026-02-25 16:19:49');
CREATE TABLE IF NOT EXISTS "articles_comments" ("id" int NOT NULL AUTO_INCREMENT PRIMARY KEY, "user_id" int not null, "article_id" int not null, "content" text not null, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id"), foreign key("article_id") references "articles"("id"));
CREATE TABLE IF NOT EXISTS "users_bans" ("id" int NOT NULL AUTO_INCREMENT PRIMARY KEY, "user_id" int not null, "admin_id" int not null, "type" varchar(255) not null default 'account', "reason" varchar(255), "expires_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id"), foreign key("admin_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "users_warnings" ("id" int NOT NULL AUTO_INCREMENT PRIMARY KEY, "user_id" int not null, "admin_id" int not null, "reason" varchar(255), "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id"), foreign key("admin_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "users_logs" ("id" int NOT NULL AUTO_INCREMENT PRIMARY KEY, "user_id" int not null, "ip" varchar(255) not null, "content" varchar(255) not null, "browser" text not null, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "navigations" ("id" int NOT NULL AUTO_INCREMENT PRIMARY KEY, "label" varchar(255) not null, "small_icon" varchar(255), "hover_icon" varchar(255), "slug" varchar(255), "order" int not null default '0', "visible" tinyint(1) not null default '1');
INSERT INTO navigations VALUES(1,'Inicio','fas fa-house-user','http://localhost:8888/images/menu/inicio.png','/',0,1);
INSERT INTO navigations VALUES(2,'HabboAcademy','fab fa-hackerrank','http://localhost:8888/images/menu/habboacademy.png',NULL,1,1);
INSERT INTO navigations VALUES(3,'Placas','fab fa-hire-a-helper','http://localhost:8888/images/menu/habbo.png',NULL,2,1);
INSERT INTO navigations VALUES(4,'Contenidos','fab fa-neos','http://localhost:8888/images/menu/conteudos.png',NULL,3,1);
INSERT INTO navigations VALUES(5,'Fan Center','fas fa-magic','http://localhost:8888/images/menu/facenter.png',NULL,4,1);
INSERT INTO navigations VALUES(6,'Radio','fas fa-music','http://localhost:8888/images/menu/radio.png',NULL,5,1);
CREATE TABLE IF NOT EXISTS "sub_navigations" ("id" int NOT NULL AUTO_INCREMENT PRIMARY KEY, "navigation_id" int not null, "label" varchar(255) not null, "slug" varchar(255), "new_tab" tinyint(1) not null default '0', "order" int not null default '0', "visible" tinyint(1) not null default '1', foreign key("navigation_id") references "navigations"("id") on delete cascade);
INSERT INTO sub_navigations VALUES(1,2,'Sobre nosotros',NULL,0,0,1);
INSERT INTO sub_navigations VALUES(2,2,'Equipo',NULL,0,0,1);
INSERT INTO sub_navigations VALUES(3,3,'Nuevas placas','/pages/nuevas-placas',0,0,1);
INSERT INTO sub_navigations VALUES(4,3,'Verificación placas','/pages/verificacion-placas',0,1,1);
INSERT INTO sub_navigations VALUES(5,5,'Generador de avatar',NULL,0,0,1);
INSERT INTO sub_navigations VALUES(6,6,'Horarios',NULL,0,0,1);
INSERT INTO sub_navigations VALUES(7,6,'Sé locutor',NULL,0,0,1);
CREATE TABLE IF NOT EXISTS "badges" ("id" int NOT NULL AUTO_INCREMENT PRIMARY KEY, "title" varchar(255) not null, "description" varchar(255), "code" varchar(255) not null, "image_path" varchar(255) not null, "rarity" varchar(255) not null default 'normal', "content_slug" varchar(255), "created_at" datetime, "updated_at" datetime);
INSERT INTO badges VALUES(1,'Academy Staff','Sou staff da Academy!','STAFF','https://images.habbo.com/c_images/album1584/ADM.gif','staff',NULL,'2026-02-25 16:19:49','2026-02-25 16:19:49');
CREATE TABLE IF NOT EXISTS "user_badges" ("user_id" int not null, "badge_id" int not null, foreign key("user_id") references "users"("id") on delete cascade, foreign key("badge_id") references "badges"("id") on delete cascade);
INSERT INTO user_badges VALUES(1,1);
CREATE TABLE IF NOT EXISTS "user_notifications" ("id" int NOT NULL AUTO_INCREMENT PRIMARY KEY, "to_user_id" int not null, "from_user_id" int not null, "type" varchar(255) not null default 'info', "title" varchar(255) not null, "slug" varchar(255), "user_saw" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("to_user_id") references "users"("id"), foreign key("from_user_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "furni_categories" ("id" int NOT NULL AUTO_INCREMENT PRIMARY KEY, "name" varchar(255) not null, "icon" varchar(255));
INSERT INTO furni_categories VALUES(1,'Sorveteiras',NULL);
INSERT INTO furni_categories VALUES(2,'Totens',NULL);
INSERT INTO furni_categories VALUES(3,'Serpentes',NULL);
INSERT INTO furni_categories VALUES(4,'Aleatórios',NULL);
INSERT INTO furni_categories VALUES(5,'Raros de Diamante',NULL);
INSERT INTO furni_categories VALUES(6,'Ventiladores',NULL);
INSERT INTO furni_categories VALUES(7,'Tronos',NULL);
INSERT INTO furni_categories VALUES(8,'Customizados',NULL);
INSERT INTO furni_categories VALUES(9,'Portas Sci-Fi',NULL);
INSERT INTO furni_categories VALUES(10,'Toldos',NULL);
INSERT INTO furni_categories VALUES(11,'Sacos de Dormir',NULL);
INSERT INTO furni_categories VALUES(12,'Pilares',NULL);
INSERT INTO furni_categories VALUES(13,'Máquinas de Fumaça',NULL);
INSERT INTO furni_categories VALUES(14,'Sofás',NULL);
INSERT INTO furni_categories VALUES(15,'Mamutes',NULL);
INSERT INTO furni_categories VALUES(16,'Guarda-Sol',NULL);
INSERT INTO furni_categories VALUES(17,'Chafariz',NULL);
INSERT INTO furni_categories VALUES(18,'Catracas',NULL);
INSERT INTO furni_categories VALUES(19,'Bonnies',NULL);
INSERT INTO furni_categories VALUES(20,'Âmbares',NULL);
INSERT INTO furni_categories VALUES(21,'Pisos Raros',NULL);
INSERT INTO furni_categories VALUES(22,'Ovos',NULL);
INSERT INTO furni_categories VALUES(23,'Máquina de Refrigerante',NULL);
INSERT INTO furni_categories VALUES(24,'Leviathans',NULL);
INSERT INTO furni_categories VALUES(25,'Holos',NULL);
CREATE TABLE IF NOT EXISTS "furni_values" ("id" int NOT NULL AUTO_INCREMENT PRIMARY KEY, "name" varchar(255) not null, "category_id" int not null, "admin_id" int not null, "price" int, "price_type" varchar(255) not null default 'coins', "state" varchar(255) not null default 'regular', "icon_path" varchar(255), "image_path" varchar(255) not null, "created_at" datetime, "updated_at" datetime, foreign key("category_id") references "furni_categories"("id"), foreign key("admin_id") references "users"("id"));
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE INDEX "password_resets_email_index" on "password_resets" ("email");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE UNIQUE INDEX "topics_categories_name_unique" on "topics_categories" ("name");
CREATE UNIQUE INDEX "badges_code_unique" on "badges" ("code");
CREATE INDEX "user_badges_user_id_index" on "user_badges" ("user_id");
CREATE INDEX "user_badges_badge_id_index" on "user_badges" ("badge_id");
CREATE UNIQUE INDEX "users_username_unique" on "users" ("username");
CREATE UNIQUE INDEX "users_habbo_name_hotel_unique" on "users" ("habbo_name", "habbo_hotel");
SET FOREIGN_KEY_CHECKS=1;
